### PR TITLE
Facebook Fix (team 1)

### PR DESCRIPTION
**Pull request by MartinJakomin**
After painfully long day, I have finally done it :S

PS: It seems like branching inherits commits. Why is that usefull ? It just overcomplicate the whole thing.

### CODE REVIEW

**Comment by mitar** [comment]
Jupiii!

**Comment by mitar** [comment]
Simply? Branches are branches in the commit tree, all commits before it are also included if those commits are not in repository you are pushing to.

**Comment by MartinJakomin** [comment]
The thing is, I can not get rid of commits in our master branch, and every branch made from master will have that commits inherited (about 14 of them).
Also I dont think that u are correct here, because our master branch is exactly the same as your master (no changed files whatsoever) but commits are stil there when I try to pull !!
Is there anyway to delete them, or any way reset master branch ?

**Comment by mitar** [comment]
Yes, you should never have in your master branch anything else except commits in from official repository. Otherwise you will/are having big problems.

I am not sure what is the best procedure here. Maybe check Google? When I have my own personal forks, I just delete the whole fork and create a new one. :-) But if there are many people working ... But probably you should do the same. Just take care you have your code stored somewhere and then put it again there.

**Pull request merged**
