### PR TITLE
Issue 173 rev1 (team4)

### PR DESCRIPTION
**Pull request by agiz**

### CODE REVIEW

**Comment by agiz** [comment]
For issue #173.

**Comment by mitar** [comment]
Don't use nodewatcher's Google Maps code because it uses deprecated API. Please use new Google Maps API.

We also do not need to display all nodes. We will display only location of current node (the node user is connected to or is closest to the user), the rest is not important. If users wants to browse all nodes then she should go to nodewatcher.

Also status of nodes is not important. Here we are just interested in existence and location of nodes, not their status.

So everything could be much much simplified. We need only one simple map with one location of one node (available in `request.node`). And then on this map we draw also events and other information.

**Comment by mitar** [comment]
Please update to new code from main repository.

**Comment by agiz** [comment]
I will update to Google Maps V3 but please specify this issue in more in details. Do not want to oppose your reasoning but technically this pull request satisfies ticket #173. 

I know that displaying all nodes will not be in final version but I worked with what I had/have. Maybe it is too soon to work on this issue due to yet unpredictable mechanisms to get required data. So in order to avoid further de-railed coding, give more details to this pull request before I update this (or even create new issue) with main repository.

**Comment by mitar** [comment]
You do not have to worry about getting data. This is now taken care of. You have API (node object in `request.node`) and this is all you need, I hope. ;-)

So just  display a small map, put node there. Display some info about the node and link to its webpage. You can differentiate between node to which user is connected to or node to which user is just close to (not much, just some text or something).

If you really want to complicate, you could display a warning somewhere for case when we are displaying a "close" node to the user if real distance between the node and the user is larger then some limit (like more than 100 m).

**Comment by agiz** [comment]
Closing in favor of https://github.com/wlanslovenija/PiplMesh/pull/201.

**Pull request closed without merging**
