### PR TITLE
Pull request for issue #1

### PR DESCRIPTION
**Pull request by aljana**
Pull request for issue #1. Static html page with some basic CSS with (temporary :)) logo on the left and google search on the right.

### CODE REVIEW

**Comment by mitar** [comment]
Fiuu. Great!

**Comment by mitar** [comment]
OK. Good work. But bad pull request. Commit 60e133a is not the way to do things. You have to make a new branch and use `git cherry-pick` to add only those commits which are really part of the pull request (first testing commits are not). So please split those commits into multiple pull requests.

Do not delete README file!

**Comment by aljana** [comment]
How do we make new branch with no commits? It seems impossible because there always appear previous commits from master branch in it.

**Comment by mitar** [comment]
I wrote on the forum. You first have to `git checkout` to the revision you want to branch from (in this case from the initial). You branch from the revision you are in.

**Pull request closed without merging**
