### PR TITLE
Pull request for issue #120  #team2

### PR DESCRIPTION
**Pull request by ghost**
#120: Layout changed to default Django 1.4 layout.

### CODE REVIEW

**Comment by mitar** [comment]
Hm. Wouldn't it be maybe better to simply move `manage.py` file one directory up?

**Comment by mitar** [comment]
Often you have scripts in the top dir (like scripts to run tests, so now also to run the site).

**Comment by ghost** [comment]
I don't know, I think that it is better if the website is separated from documentation?

**Comment by mitar** [comment]
But website (code) is. Only scripts to run things can be in top-level. We will also have other such scripts later on there, you will see. This is also why they have changed the layout in this way. To remove this script from the code, so that one is code, the other is script to run it.

**Comment by ghost** [comment]
Corrected.

**Pull request merged**
