### PR TITLE
Issue#95 Login design

### PR DESCRIPTION
**Pull request by cardawid**
New login desing.

### CODE REVIEW

**Comment by cardawid** [comment]
I wan't to add some own created buttons if that is ok. And I copied some code from Domen's commit because i was in the middle of making this design when he commited his own :)

**Comment by mitar** [comment]
Please update from main repository and we can see how it goes further.

**Comment by cardawid** [comment]
There is one problem. When i synced my map with main repository i got conflicts in code. How can i fix that ?

**Comment by mitar** [comment]
Yes, this is normal. Now you have to manually edit the files with conflicts and resolve them. This means that you have to see where in the file are sections marked with `>>>` and `<<<` characters and combine them in a meaningful way, removing those marks in the process. And then you `git add` those files and commit everything. Read on the Internet more about resolving merge conflicts in git.

**Pull request closed without merging**
