### PR TITLE
Fixed TODO: method validate_unique (Team 5)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mitar** [comment]
What exactly do you think `validate_unique` should do?

**Comment by ghost** [comment]
It checks forms that are set to be unique if they are unique right?

**Comment by mitar** [comment]
Yes. And your code does what? So do you know what your code does?

**Comment by mitar** [comment]
So we talked about this today and the point is that `validate_unique` should simply do nothing (pass) in our case. If you check Django implementation, it calls `validate_unique` on model instance, and our MongoEngine objects do not have this. So, just do `pass`, but comment/explain it accordingly.

**Comment by ghost** [comment]
Fixed now, next time I will actually read the code. :)

**Pull request merged**
