### PR TITLE
Part od Issue #86

### PR DESCRIPTION
**Pull request by domenc**
Remove X from search bar and display "See your results" only on search page

### CODE REVIEW

**Comment by domenc** [comment]
I have few questions:
- Past search query string should be visible on result page: How can I make this? With database history?
- Design the whole search input box as Firefox home search box: Add Image "Google" left od the search box and delete from input box?
- We should also have adds on the right side of the results?: Do you mean ads?

**Comment by mitar** [comment]
> Past search query string should be visible on result page

No, this just means that you prefill the search box from `q` query parameter.

> Add Image "Google" left od the search box and delete from input box?

Yes, add "Google". What delete?

> Do you mean ads?

Yes. :-)

**Comment by mitar** [comment]
BTW, this pull request was pulled in.

**Comment by domenc** [comment]
OK, I will add Image and add query on result page, but no ads (this is bad).

**Comment by mitar** [comment]
Why are ads bad? Would you rather pay with money for your services on the Internet? The payment on the Internet is: ads or privacy. Because you pay with that, you do not have to pay with money. You can always pay with money Gmail and do not get ads, you know that? Are you doing that? No.

Would it be possible to have this optional? Like a user value which would enable or disable this for given user? And then we could have like users who would get awarded and not be given ads?

**Pull request merged**
