### PR TITLE
Pull request for Issue #123

### PR DESCRIPTION
**Pull request by aljana**
Added language support for logo.

### CODE REVIEW

**Comment by mitar** [comment]
You are working from non-latest repository. I cannot merge.

**Comment by aljana** [comment]
Ok sorry, I'm closing this one.

**Comment by mitar** [comment]
You could probably just pull from the main repository into it and merge? No need to do new pull requests.

**Comment by aljana** [comment]
But I made it already..

**Comment by mitar** [comment]
No problem. I will use that one. But that you know for future.

**Pull request closed without merging**
